import React, { useState } from 'react';
import { StyleSheet, Text, View, FlatList, TouchableOpacity, Modal, TouchableWithoutFeedback, Keyboard, Image } from 'react-native';
import { globalStyles, images } from '../styles/global';
import Header from '../shared/header';
import Card from '../shared/card';
import moment from 'moment';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import EntryForm from './entryForm';

export default function Home({ navigation }) {

  // Modal for new entries
  const [modalOpen, setModalOpen] = useState(false);

  // TODO: only entries of the last day (if more than one) OR the last n=10? entries of several days OR the last entries of the current week? (all entries via Calendar)
  // if the last entries of the current week: need for a no-entry-last-week-screen
  const [entries, setEntries] = useState([ 
    {title: "overjoyed entry", content: "overjoyed overjoyed overjoyed", mood: "5", key: "1599949186"}, 
    {title: "happy entry", content: "happy happy happy", mood: "4", key: "1599948186"}, 
    {title: "neutral entry", content: "neutral neutral neutral", mood: "3", key: "1599947186"}, 
    {title: "sad entry", content: "sad sad sad", mood: "2", key: "1599946186"}, 
    {title: "angry entry", content: "angry angry angry", mood: "1", key: "1599945186"}, 
    {title: "My third autogenerated entry", content: "...just some more dummy data...", mood: "4", key: "1599034186"}, 
    {title: "My second autogenerated entry", content: "...just some dummy data...", mood: "3", key: "1598974186"}, 
    {title: "My first, but autogenerated entry", content: "Welcome to Tagebuch App and thanks for giving it a try! This Screen is the EntryDetailsScreen of the entry you just tipped on in the HomeScreen. To Return to HomeScreen use the left arrow in the top left corner. You can navigate between HomeScreen and AboutScreen via the list icon in the HomeScreen Header or swiping from left display border to the right. To create a new entry, in HomeScreen click on the edit icon centered bellow the Header. An entry mask will popup from the bottom, where you can insert the title, content and your mood (all required). Drop the entry by clicking the 'X'. Above all: Have a nice day! (Or blast this app with a bad mood drop..)", mood: "5", key: "1598433300"}
  ])

  const addEntry = (entry) => {
    entry.key = (moment().unix()).toString();
    setEntries((currEntries) => {
      return [ entry, ...currEntries]
    });
    setModalOpen(false);
  }
  /*
    failled to compile bla:
    expo install react-native-gesture-handler react-native-reanimated react-native-screens react-native-safe-area-context @react-native-community/masked-view
  */   

  return (
    <View style={globalStyles.container}>
      {/* Modal for new Entries: loads EntryForm */}
      <Modal visible={modalOpen} animationType='slide'>
        <TouchableWithoutFeedback onPress={Keyboard.dismiss}>
          <View style={styles.modalContent}>
            <MaterialCommunityIcons 
              name="close" 
              size={24} 
              style={{...styles.modalToggle, ...styles.modalClose}} 
              onPress={() => setModalOpen(false)} 
            />
            <EntryForm addEntry={addEntry} />
          </View>
        </TouchableWithoutFeedback>
      </Modal>
      {/* 'button (icon) to open the Modal */}
      <MaterialCommunityIcons 
        name="playlist-edit" 
        size={24} 
        style={styles.modalToggle}
        onPress={() => setModalOpen(true)}
      />

      <FlatList 
        data={entries}
        renderItem={({ item }) => (
          <TouchableOpacity onPress={() => navigation.navigate('EntryDetails', item)}>
            <Card>
              <View style={styles.homeCard}>
                <Image 
                  source={images.moods[item.mood]} 
                  style={styles.cardImage}
                />
                <View style={styles.homeCardInner}>
                  <Text style={globalStyles.titleText}>{ moment.unix(item.key).fromNow() }</Text>
                  <Text style={globalStyles.paragraph}>{ item.title }</Text>
                </View>
              </View>
            </Card>
          </TouchableOpacity>
        )}
      />
    </View>
  );
} 

const styles = StyleSheet.create({
  modalContent: {
    flex: 1,
  },
  modalToggle: {
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#d3d3d3',
    backgroundColor: '#fff',
    padding: 10,
    borderRadius: 10,
    alignSelf: 'center'
  },
  modalClose: {
    marginTop: 20,
    marginBottom: 0
  },
  homeCard: {
    flexDirection: 'row',
    alignItems: 'center'
  },
  cardImage: {
    width: 50,
    height: 50,
    marginRight: 10
  },
  homeCardInner: {
    flexDirection: 'column',
    marginRight: 25,
    paddingRight: 25 
  }
});