export const data = [
  {title: "overjoyed entry", content: "overjoyed overjoyed overjoyed", mood: "5", date: "2020-09-13", key: "1599949186"}, 
  {title: "happy entry", content: "happy happy happy", mood: "4", date: "2020-09-13", key: "1599948186"}, 
  {title: "neutral entry", content: "neutral neutral neutral", mood: "3", date: "2020-09-12", key: "1599947186"}, 
  {title: "sad entry", content: "sad sad sad", mood: "2", date:'2020-09-12', key: "1599946186"}, 
  {title: "angry entry", content: "angry angry angry", mood: "1", date: "2020-09-12", key: "1599945186"}, 
  {title: "My third autogenerated entry", content: "...just some more dummy data...", mood: "4", date:"2020-09-02", key: "1599034186"}, 
  {title: "My second autogenerated entry", content: "...just some dummy data...", mood: "3", date: "2020-09-01", key: "1598974186"}, 
  {title: "My first, but autogenerated entry", content: "Welcome to Tagebuch App and thanks for giving it a try! This Screen is the EntryDetailsScreen of the entry you just tipped on in the HomeScreen. To Return to HomeScreen use the left arrow in the top left corner. You can navigate between HomeScreen and AboutScreen via the list icon in the HomeScreen Header or swiping from left display border to the right. To create a new entry, in HomeScreen click on the edit icon centered bellow the Header. An entry mask will popup from the bottom, where you can insert the title, content and your mood (all required). Drop the entry by clicking the 'X'. Above all: Have a nice day! (Or blast this app with a bad mood drop..)", mood: "5", date: "2020-08-26", key: "1598433300"}
];